# coding: utf-8

"""
    Tracking API

    <p>An API for CRUD of sample tracking information for Mykrobe Atlas project <p>This API is intended to satisfy the following user stories <li> Atlas user wants to know the sample status so that I can know if specific results are available <li> Atlas user wants to know QC results for a sample so that I can know if a specific sample has passed QC check <li> Atlas user wants to deprecate a sample so that it is no longer available from the Atlas system <li> sample ingestion service wants to know if a sample already exists so that I can decide on rejecting a sample <li> sample ingestion service wants to know if a file already exists so that I can know if this is a new file <li> sample ingestion service wants to add a new sample for tracking so that It can know if the sample is accepted <li> sample processing service wants to add a processing event for a new sample so that the sample can be auditted <li> sampel processing service wants to add QC results for a new sample so that other user can know if the new sample passes the QC check <li> sampel processing service wants to update sample status so that they are up to date <li> sampel processing service wants to update sample's QC results so that they are up to date <li> audit user wants to know all the processing events for a sample so that I can know what happened to a sample  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "tracking_client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Tracking API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Tracking API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    &lt;p&gt;An API for CRUD of sample tracking information for Mykrobe Atlas project &lt;p&gt;This API is intended to satisfy the following user stories &lt;li&gt; Atlas user wants to know the sample status so that I can know if specific results are available &lt;li&gt; Atlas user wants to know QC results for a sample so that I can know if a specific sample has passed QC check &lt;li&gt; Atlas user wants to deprecate a sample so that it is no longer available from the Atlas system &lt;li&gt; sample ingestion service wants to know if a sample already exists so that I can decide on rejecting a sample &lt;li&gt; sample ingestion service wants to know if a file already exists so that I can know if this is a new file &lt;li&gt; sample ingestion service wants to add a new sample for tracking so that It can know if the sample is accepted &lt;li&gt; sample processing service wants to add a processing event for a new sample so that the sample can be auditted &lt;li&gt; sampel processing service wants to add QC results for a new sample so that other user can know if the new sample passes the QC check &lt;li&gt; sampel processing service wants to update sample status so that they are up to date &lt;li&gt; sampel processing service wants to update sample&#39;s QC results so that they are up to date &lt;li&gt; audit user wants to know all the processing events for a sample so that I can know what happened to a sample  # noqa: E501
    """
)
